### ISSUE TITLE
Cannot deploy container

### ISSUE THREAD

**Issue by jeovanevs** [OpenNebula/addon-lxdone#21]
Hi everyone!
I just installed the LXDone on a new Opennebula installation following the installation tutorial, but when I tried to deploy the VM provided in the marketplace (ID: 7dd50db7-33c4-4b39-940c-f6a55432622f) it failed. Can any one help me, please.

The opennebula is configured as an stand alone server. The kvm driver is working and deploying VMs normally, and the 'lxc launch' command either.

VM log:
```
Mon Sep 25 18:11:28 2017 [Z0][VM][I]: New state is ACTIVE
Mon Sep 25 18:11:28 2017 [Z0][VM][I]: New LCM state is PROLOG
Mon Sep 25 18:11:29 2017 [Z0][VM][I]: New LCM state is BOOT
Mon Sep 25 18:11:29 2017 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/14/deployment.0
Mon Sep 25 18:11:30 2017 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Mon Sep 25 18:11:30 2017 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/lxd/deploy '/var/lib/one//datastores/0/14/deployment.0' 'localhost' 14 localhost
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: deploy.py: ########################################
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: losetup: /var/lib/one/datastores/0/14/disk.0: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: mount: wrong fs type, bad option, bad superblock on /dev/loop0,
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: missing codepage or helper program, or other error
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]:
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: In some cases useful info is found in syslog - try
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: dmesg | tail or so.
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: Traceback (most recent call last):
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: File "/var/tmp/one/vmm/lxd/deploy.py", line 154, in
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: apply_profile(profile, container)
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: File "/var/tmp/one/vmm/lxd/deploy.py", line 114, in apply_profile
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: lc.storage_context(container, contextiso)
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: File "/var/tmp/one/vmm/lxd/lxd_common.py", line 187, in storage_context
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: container.files.put('/mnt/' + i.name, i.content)
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: File "/usr/lib/python2.7/dist-packages/pylxd/container.py", line 78, in put
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: params={'path': filepath}, data=data)
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: File "/usr/lib/python2.7/dist-packages/pylxd/client.py", line 94, in post
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: self._assert_response(response, allowed_status_codes=(200, 201, 202))
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: File "/usr/lib/python2.7/dist-packages/pylxd/client.py", line 66, in _assert_response
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: raise exceptions.LXDAPIException(response)
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: pylxd.exceptions.LXDAPIException: file does not exist
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: ExitCode: 1
Mon Sep 25 18:11:31 2017 [Z0][VMM][I]: Failed to execute virtualization driver operation: deploy.
Mon Sep 25 18:11:31 2017 [Z0][VMM][E]: Error deploying virtual machine
Mon Sep 25 18:11:31 2017 [Z0][VM][I]: New LCM state is BOOT_FAILURE
```
```
oneadmin@max:~$ ll datastores/0/14
total 243076
drwxrwxr-x 2 oneadmin oneadmin        54 Sep 25 18:11 ./
drwxr-xr-x 3 oneadmin oneadmin        16 Sep 25 18:11 ../
-rw-rw-r-- 1 oneadmin oneadmin      3305 Sep 25 18:11 deployment.0
-rw-r--r-- 1 oneadmin oneadmin 248529635 Sep 25 18:11 disk.0
-rw-r--r-- 1 oneadmin oneadmin    372736 Sep 25 18:11 disk.1
```

lxc info:
```
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.235.2.225:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFPTCCAyWgAwIBAgIQVu8i4gpyY...
    -----END CERTIFICATE-----
  certificate_fingerprint: e6a7dd45....
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-96-generic
  server: lxd
  server_pid: 460
  server_version: 2.0.10
  storage: dir
  storage_version: ""
```
``` 
oneadmin@max:~$ lxc list
+--------+---------+------+------+------------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+--------+---------+------+------+------------+-----------+
| one-14 | STOPPED |      |      | PERSISTENT | 0         |
+--------+---------+------+------+------------+-----------+
```
```
oneadmin@max:~$ losetup
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /vmfs/datastores/0/14/disk.0
```
```
root@max:~# mount /dev/loop0 /mnt/
mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

root@max:~# dmesg | tail
[13435.322510] audit: type=1400 audit(1506372931.308:42): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default" pid=63940 comm="apparmor_parser"
[13435.322520] audit: type=1400 audit(1506372931.308:43): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-cgns" pid=63940 comm="apparmor_parser"
[13435.322526] audit: type=1400 audit(1506372931.308:44): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-mounting" pid=63940 comm="apparmor_parser"
[13435.322532] audit: type=1400 audit(1506372931.308:45): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-nesting" pid=63940 comm="apparmor_parser"
[13574.967436] audit: type=1400 audit(1506373070.948:46): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/bin/lxc-start" pid=453 comm="apparmor_parser"
[13574.980193] audit: type=1400 audit(1506373070.960:47): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default" pid=458 comm="apparmor_parser"
[13574.980205] audit: type=1400 audit(1506373070.960:48): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-cgns" pid=458 comm="apparmor_parser"
[13574.980213] audit: type=1400 audit(1506373070.960:49): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-mounting" pid=458 comm="apparmor_parser"
[13574.980220] audit: type=1400 audit(1506373070.960:50): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-nesting" pid=458 comm="apparmor_parser"
[15595.453903] audit: type=1400 audit(1506375091.368:51): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-one-14_</var/lib/lxd>" pid=24195 comm="apparmor_parser"
```
```
lsee@max:~$ sudo mkfs.ext4 /dev/loop0
mke2fs 1.42.13 (17-May-2015)
Discarding device blocks: done
Creating filesystem with 242704 1k blocks and 60720 inodes
Filesystem UUID: 997a0a16-69de-4b2c-b4bd-c56feb56d011
Superblock backups stored on blocks:
        8193, 24577, 40961, 57345, 73729, 204801, 221185

Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

lsee@max:~$ sudo mount /dev/loop0 /mnt/
lsee@max:~$ ls -la /mnt/
total 13
drwxr-xr-x  3 root root  1024 Sep 25 19:27 .
drwxr-xr-x 23 root root   322 Sep 24 06:53 ..
drwx------  2 root root 12288 Sep 25 19:27 lost+found
lsee@max:~$ sudo ls -la /mnt/lost+found/
total 13
drwx------ 2 root root 12288 Sep 25 19:27 .
drwxr-xr-x 3 root root  1024 Sep 25 19:27 ..
```

I don't know if the following command should work, but anyway I tried:
```
oneadmin@max:~$ lxc start one-14
error: Error calling 'lxd forkstart one-14 /var/lib/lxd/containers /var/log/lxd/one-14/lxc.conf': err='Failed to run: /usr/bin/lxd forkstart one-14 /var/lib/lxd/containers /var/log/lxd/one-14/lxc.conf: '
  lxc 20170925213131.423 ERROR lxc_conf - conf.c:mount_rootfs:798 - No such file or directory - Failed to get real path for "/var/lib/lxd/containers/one-14/rootfs".
  lxc 20170925213131.423 ERROR lxc_conf - conf.c:setup_rootfs:1220 - Failed to mount rootfs "/var/lib/lxd/containers/one-14/rootfs" onto "/usr/lib/x86_64-linux-gnu/lxc" with options "(null)".
  lxc 20170925213131.423 ERROR lxc_conf - conf.c:do_rootfs_setup:3899 - failed to setup rootfs for 'one-14'
  lxc 20170925213131.423 ERROR lxc_conf - conf.c:lxc_setup:3981 - Error setting up rootfs mount after spawn
  lxc 20170925213131.423 ERROR lxc_start - start.c:do_start:811 - Failed to setup container "one-14".
  lxc 20170925213131.423 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
  lxc 20170925213131.424 ERROR lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "one-14".
  lxc 20170925213131.998 ERROR lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
  lxc 20170925213131.998 ERROR lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "one-14".
```
Any Idea why I' m getting this problem?

Thanks!

**Comment by jmdelafe** [comment]
It seems a problem with the image in marketplace. It's compressed and the driver it's trying to mount a .gz file. As a workaround you can download the [image from marketplace](https://marketplace.opennebula.systems/appliance/7dd50db7-33c4-4b39-940c-f6a55432622f), decompress it and upload the .img file to OpenNebula datastore. This will work just fine :)

We will fix this problem as soon as possible.

**Comment by jeovanevs** [comment]
## [SOLVED]
 **It was a problem with the image indeed.** 
I downloaded the @jmdelafe [image ](https://opennebula.org/lxdone-lightweight-virtualization-for-opennebula/comment-page-1/#comment-146169) and tried to mount as a loop device and it worked. So I upload it as path to opennebula and it work just fine.
Thank you @jmdelafe I will try with the marketplace image too as you said.
